language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache

before_install:
  - npm i -g firebase-tools
install:
  - npm i

before_script:
  - npm test
  - npm start:prod -- --silent &
script:
  - $(npm bin)/cypress run
after_success:
  - yarn release
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN
branches:
  only:
    - master